const DATES=['8/24','8/25','8/26','8/27','8/28'];
const etfs=[['00400A','主動國泰動能高息'],['00401A','主動摩根台灣鑫收'],['00402A','主動安聯美國科技'],['00403A','主動統一升級50'],['00404A','主動聯博動能50'],['00405A','主動富邦台灣龍耀'],['00406A','主動中信台灣收益'],['00407A','主動凱基台灣'],['00408A','主動第一金優股息'],['00410A','主動永豐科技趨勢'],['00980A','主動野村臺灣優選'],['00981A','主動統一台股增長'],['00982A','主動群益台灣強棒'],['00983A','主動中信ARK創新'],['00984A','主動安聯台灣高息成長'],['00985A','主動野村臺灣50'],['00986A','主動台新龍頭成長'],['00987A','主動台新優勢成長'],['00988A','主動統一全球創新'],['00989A','主動摩根美國科技'],['00990A','主動元大AI新經濟'],['00991A','主動復華未來50'],['00992A','主動群益科技創新'],['00993A','主動安聯台灣'],['00994A','主動第一金台股優'],['00995A','主動中信台灣卓越'],['00996A','主動兆豐台灣豐收'],['00997A','主動群益美國增長'],['00999A','主動野村臺灣高息']].map((x,i)=>({code:x[0],name:x[1],buy:i===11?'27.8億':(1.2+(i%7)*.73).toFixed(2)+'億',sell:i===11?'15.6億':(.8+(i%5)*.91).toFixed(2)+'億',net:i===11?'+12.2億':((((1.2+(i%7)*.73)-(.8+(i%5)*.91))>=0?'+':'')+((1.2+(i%7)*.73)-(.8+(i%5)*.91)).toFixed(2)+'億'),count:(5+i%14)+'檔'}));
const reportData=[{code:'00981A',name:'主動統一台股增長',days:[{state:'zero'},{net:6.81,b:['創意 4.29億｜70張','奇鋐 2.52億｜80張'],s:[]},{net:-1.59,b:['華星光 4.62億｜749張','台達電 3.72億｜210張','京元電子 1.24億｜500張'],s:['信驊 6.59億｜42張','萬潤 2.60億｜200張','台光電 1.98億｜36張']},{net:-20.48,b:['京元電子 2.41億｜893張'],s:['台積電 15億｜620張','信驊 4.29億｜28張','萬潤 2.79億｜195張']},{state:'missing'}]},{code:'00403A',name:'主動統一升級50',days:[{net:-3.57,b:['奇鋐 2.95億｜100張','南亞 1.89億｜1000張'],s:['聯鈞 7.46億｜1400張']},{net:7.93,b:['景碩 2.64億｜300張','緯穎 2.04億｜30張'],s:['台達電 2.80億｜160張']},{net:-19.15,b:['大立光 5.12億｜74張'],s:['聯電 11.85億｜10000張','日月光投控 6.05億｜1000張']},{net:-17.66,b:['大立光 4.24億｜60張'],s:['台積電 21.78億｜900張','華邦電 5.45億｜3000張']},{state:'missing'}]},{code:'00991A',name:'主動復華未來50',days:[{state:'zero'},{net:-14.58,b:[],s:['台積電 7.25億｜300張','旺矽科技 5.04億｜100張']},{net:-1.79,b:['聯亞 3.26億｜100張'],s:['旺矽科技 5.04億｜100張']},{net:-8.91,b:[],s:['台積電 4.84億｜200張','旺矽科技 4.07億｜80張']},{state:'missing'}]}];
const stocks=['台積電 2330','信驊 5274','大立光 3008','旺矽 6223','萬潤 6187','緯穎 6669','富世達 6805','創意 3443'];let etfIndex=Math.max(0,etfs.findIndex(x=>x.code==='00981A')),stockIndex=0;
function formatDay(d){if(d.state==='missing')return '<div class="dcell"><div class="dnet wait">持股資料　缺</div><span class="flow">被贖回：來源待更新</span><div class="waittxt" style="font-size:15px;text-align:center;margin-top:30px">缺</div></div>';if(d.state==='zero')return '<div class="dcell"><div class="dnet" style="color:#808991">當日異動　0</div><span class="flow">申購缺</span><div style="font-size:12px;color:#8b949c;text-align:center;margin-top:25px">0</div></div>';let cls=d.net>=0?'buy':'sell',lines=[...(d.b||[]).map(x=>`<div class="dline buytxt">• ${x}</div>`),...(d.s||[]).map(x=>`<div class="dline selltxt">• ${x}</div>`)];return `<div class="dcell"><div class="dnet ${cls}">持股淨額　${d.net>=0?'+':''}${d.net.toFixed(2)}億</div><span class="flow">申購缺</span>${lines.join('')}</div>`}
function renderReport(){document.getElementById('reportRows').innerHTML=reportData.map(r=>`<div class="mrow"><div class="ecode">${r.code}<small>${r.name}</small></div>${r.days.map(formatDay).join('')}</div>`).join('');fitReport()}
function fitReport(){const stage=document.getElementById('reportStage'),canvas=document.getElementById('reportCanvas');if(!stage||!canvas)return;const w=stage.clientWidth||window.innerWidth-14,scale=Math.min(w/540,1.35);canvas.style.transform=`scale(${scale})`;stage.style.height=(960*scale)+'px'}
function showPage(p){['report','etf','eps','import'].forEach(id=>document.getElementById(id+'Page').classList.toggle('hidden',id!==p));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='etf')renderETF();scrollTo(0,0)}
function stepEtf(n){etfIndex=Math.max(0,Math.min(etfs.length-1,etfIndex+n));renderETF()}
function renderETF(){const e=etfs[etfIndex];etfCode.textContent=e.code;etfName.textContent=e.name;etfPos.textContent=`${etfIndex+1}/${etfs.length}`;etfPrev.disabled=etfIndex===0;etfNext.disabled=etfIndex===etfs.length-1;etfBuy.textContent=e.buy;etfSell.textContent=e.sell;etfNet.textContent=e.net;etfCount.textContent=e.count;etfDateCards.innerHTML=DATES.map((d,i)=>`<div class="datecard"><b>${d}</b><span class="${i===4?'warn':i%2?'buy':'sell'}">${i===4?'持股資料缺':i===0?'已驗證零異動':i%2?'+2.40億':'-2.56億'}</span></div>`).join('');let names=['聯亞','聯電','穩懋','力旺','高力','萬海','旺矽','奇鋐','宜鼎','群聯','創見','威剛'];let rows=names.map((n,i)=>`<div class="smrow"><div class="sname">${n}<small>${2300+i*17}</small></div>${DATES.map((d,j)=>{if(j===4)return '<div class="missing">缺</div>';if((i+j)%4===0)return '<div class="zero">—</div>';let buy=(i+j)%3===0;return `<div class="${buy?'buy':'sell'}">${buy?'+':'-'}${(.2+i*.08+j*.12).toFixed(2)}億<small>${20+i*5+j*3}張</small></div>`}).join('')}<div class="total ${i%2?'sell':'buy'}">${i%2?'-':'+'}${(.8+i*.13).toFixed(2)}億</div></div>`).join('');etfStockMatrix.innerHTML=`<div class="smhead"><div>標的</div>${DATES.map(d=>`<div>${d}</div>`).join('')}<div>5日</div></div>${rows}`}
function openStock(i){stockIndex=Math.max(0,Math.min(stocks.length-1,i));stockModal.classList.add('open');document.body.style.overflow='hidden';renderStock()}
function closeStock(){stockModal.classList.remove('open');document.body.style.overflow=''}
function stepStock(n){stockIndex=Math.max(0,Math.min(stocks.length-1,stockIndex+n));renderStock()}
function renderStock(){stockTitle.textContent=stocks[stockIndex];stockPos.textContent=`${stockIndex+1}/${stocks.length}`;stockPrev.disabled=stockIndex===0;stockNext.disabled=stockIndex===stocks.length-1;let rows=etfs.map((e,i)=>`<div class="rtrow"><div class="etf">${e.code}<small>${e.name}</small></div>${DATES.map((d,j)=>{if(j===4)return '<div class="missing">缺</div>';if((i+j+stockIndex)%4===0)return '<div>—</div>';let buy=(i+j+stockIndex)%3===0;return `<div class="${buy?'buy':'sell'}">${buy?'+':'-'}${(.48+i*.36+j*.6).toFixed(2)}億<small>${15+i*12+j*10}張</small></div>`}).join('')}<div class="${i%2?'sell':'buy'}">${i%2?'-':'+'}${(1.2+i*.54).toFixed(2)}億</div></div>`).join('');radarTable.innerHTML=`<div class="rthead"><div>ETF</div>${DATES.map(d=>`<div>${d}</div>`).join('')}<div>5日</div></div>${rows}`}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));window.addEventListener('resize',fitReport);renderReport();renderETF();
